site_name: ExportHtml Documentation
site_url: https://facelessuser.github.io/ExportHtml
repo_url: https://github.com/facelessuser/ExportHtml
edit_uri: tree/master/docs/src/markdown
site_description: Sublime Text plugin that exports code to HTML or BBCODE for copying, printing, or saving.
copyright: |
  Copyright &copy; 2012 - 2020 <a href="https://github.com/facelessuser">Isaac Muse</a>
  <br><span class="md-footer-custom-text">emoji provided free by </span>
  <a href="https://github.com/twitter/twemoji">Twemoji</a>

docs_dir: docs/src/markdown
theme:
  name: material
  custom_dir: docs/theme
  palette:
    primary: blue
    accent: blue
  logo:
    icon: description
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - About ExportHtml: index.md
  - Installation: installation.md
  - User Guide: usage.md
  - Contributing &amp; Support: contributing.md
  - License: license.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "\ue157"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      user: facelessuser
      repo: ExportHtml
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:

extra:
  social:
    - type: github
      link: https://github.com/facelessuser
extra_css:
  - extra-30d8e6755c.css
extra_javascript:
  - extra-0b9b22dd13.js
